import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import DarkModeButton from "@/Components/DarkModeButton/dark-mode-button";

export const metadata = {
  title: "Countries App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="body">
        <header className="layoutHeader">
          <h1>Where in the world?</h1>
          <DarkModeButton />
        </header>
        {children}
        </body>
    </html>
  );
}
